language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist
  - travis_retry cp .env.example .env
  - travis_retry php artisan key:generate

script: vendor/bin/phpunit